# Generated by Django 5.2.4 on 2025-07-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_city', models.CharField(max_length=100)),
                ('delivery_city', models.CharField(max_length=100)),
                ('weight_kg', models.PositiveIntegerField()),
                ('pickup_date', models.DateField()),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('MATCHED', 'Matched'), ('COMPLETED', 'Completed')], default='POSTED', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
