# Generated by Django 5.2.4 on 2025-07-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_category', models.CharField(choices=[('SAME_CITY', 'Same City'), ('NEARBY', 'Nearby'), ('REGIONAL', 'Regional'), ('LONG_DISTANCE', 'Long Distance')], max_length=20)),
                ('match_score', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
